FROM weibeld/ubuntu-networking:latest

# Generic useful tools
RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y \
    sudo \
    python3 \
    python3-pip \
    vim \
    nano \
    curl

# System daemons
RUN apt install -y telnetd
RUN apt install -y openssh-server
RUN apt install -y apache2

# tcpdump
RUN DEBIAN_FRONTEND=noninteractive apt install -y expect telnet tcpdump libcap2-bin

RUN groupadd pcap

RUN ln -s /usr/sbin/tcpdump /usr/bin/tcpdump
RUN chgrp pcap /usr/bin/tcpdump
RUN chmod 750 /usr/bin/tcpdump

RUN setcap cap_net_raw+ep /usr/sbin/tcpdump

# Postgres
RUN apt install -y postgresql-client

# Flavor
RUN apt install -y fortune cowsay

# Webserver configs
COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf

ADD ./bin /usr/bin

CMD \
    [ -n "${ENABLETELNET}" ] && service openbsd-inetd start; \
    [ -n "${ENABLESSH}" ] && service ssh start; \
    /usr/bin/add_users.sh ${USERS} && \
    /usr/bin/make_shadow_readable.sh && \
    apachectl -DFOREGROUND